server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway

gateway:
  routes:
    url: ${GATEWAY_ROUTES_URL:http://localhost:9090/routes.yaml}
    refresh-interval: ${GATEWAY_ROUTES_REFRESH_INTERVAL:5000}
